spring.application.name=linkshortener
# 1. Alamat URL Database (Ganti 'nama_db_kamu' sesuai database yang kamu buat di Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/linkshortener

# 2. Username dan Password bawaan PostgreSQL kamu
spring.datasource.username=postgres
spring.datasource.password=123456

# 3. Driver yang digunakan
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Pengaturan Tambahan Hibernate (Opsional tapi sangat membantu saat belajar)
# update = otomatis membuat/memperbarui tabel di Postgres berdasarkan kodingan Java kita nanti
spring.jpa.hibernate.ddl-auto=update
# Menampilkan query SQL yang dijalankan Spring Boot di terminal log
spring.jpa.show-sql=true

# Konfigurasi Koneksi Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Set waktu kadaluwarsa default cache (misal: 1 hari / 86400 detik)
spring.cache.redis.time-to-live=86400000